#To start locally:
# bundle exec jekyll serve
# Site settings
url: "https://limicodi.github.io"
baseurl: ""
title: Renjian Lim
#email: your.email@example.com
description: >-
  Academic researcher and professional. Personal homepage website
#twitter_username: username
#github_username: username
minimal_mistakes_skin: default
search: false

# Collections
collections:
  contents:
    output: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# No pagination needed for single-page site
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ren Jian, Lim"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : " "
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "#"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "#"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "#"
    - label: "kevinlim@bu.edu"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kevinlim@bu.edu"
